
spring:

  application:
    name: ${APP_NAME:ms-usuarios}

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql8:3306}/${DB_DATABASE:ms-usuarios}?serverTimezone=America/Bogota&allowPublicKeyRetrieval=false
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

## mostrar ejecucion de HPQL en consola
logging:
  level:
    org:
      hibernate:
        SQL: debug

  ## Guardar los logs en el contenedor docker
  file:
    path: /app/logs

server:
  port: ${PORT:8001}

## Variables de ambiente app
ms:
  cursos:
    url: ${CURSOS_URL:ms-cursos:8002}