
spring:
  application:
    name: ms-usuarios

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/ms-usuarios?serverTimezone=America/Bogota&allowPublicKeyRetrieval=false
    username: 'camilomeneses'
    password: '@cam123lo_pass'
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

logging:
  level:
    org:
      hibernate:
        SQL: debug

  ## Guardar los logs en el contenedor docker
  file:
    path: /app/logs

server:
  port: 8001

